### ISSUE TITLE
Landing error 

### ISSUE THREAD

**Issue by bbtiger** [Aang23/GlobalTab#1]
velocity-proxy-1.0.0-SNAPSHOT-all#111.jar
GlobalTab-1.0-all#24.jar

[21:34:38 INFO]: [server connection] test -> lobby has connected
[21:34:38 ERROR]: Exception in thread "Timer-0" java.lang.IllegalArgumentException: this TabList already contains an entry with the same uuid
[21:34:38 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
[21:34:38 ERROR]:       at com.velocitypowered.proxy.tablist.VelocityTabList.addEntry(VelocityTabList.java:47)
[21:34:38 ERROR]:       at com.aang23.globaltab.TimerHandler.run(TimerHandler.java:37)
[21:34:38 ERROR]:       at java.util.TimerThread.mainLoop(Unknown Source)
[21:34:38 ERROR]:       at java.util.TimerThread.run(Unknown Source)

**Comment by Aang23** [comment]
Just got the same on my Velocity instance. Thanks for reporting, I'll fix that.
