### ISSUE TITLE
Login error , GlobalTab failure

### ISSUE THREAD

**Issue by bbtiger** [Aang23/GlobalTab#2]
velocity-proxy-1.0.0-SNAPSHOT-all#145.jar
GlobalTab-1.0-all#26.jar

[20:44:55 INFO]: [server connection] smart -> lobby has connected
[20:44:56 ERROR]: Exception in thread "Timer-0" java.lang.NullPointerException
[20:44:56 ERROR]:       at com.aang23.globaltab.ConfigManager.isServerAllowed(ConfigManager.java:84)
[20:44:56 ERROR]:       at com.aang23.globaltab.TimerHandler.run(TimerHandler.java:24)
[20:44:56 ERROR]:       at java.util.TimerThread.mainLoop(Unknown Source)
[20:44:56 ERROR]:       at java.util.TimerThread.run(Unknown Source)

**Comment by Aang23** [comment]
Could you send me your config as well?

**Comment by bbtiger** [comment]
{
  "footer":"&7%playercount% !",
  "customtabs":[
    "&3Your ping : &e%ping%",
    "&3服务器: &e%server%",
    "&3Balance : &e%balance%"
  ],
  "header":"&4欢迎, &6%username%&4 ",
  "updatedelay":"1",
  "player_format":"%prefix% %username%",
  "customtabsenabled":true
}

**Comment by Aang23** [comment]
Build 27 should fix that. However you config is outdated, and you should copy it elsewhere, delete it, and paste your settings back.

**Comment by bbtiger** [comment]
ＯＫ，Thank you！

**Comment by Aang23** [comment]
You're welcome!
