### ISSUE TITLE
Error with luckperm

### ISSUE THREAD

**Issue by jehendeoff** [Aang23/GlobalTab#8]
Actually, I only wanted a global tab, and I found this plugins for velocity.

But I have a major problem, I needed luckperm for globaltab because it throw the error : 
`
[16:29:57 INFO]: Connections will use epoll channels, native (Linux amd64) compression, Java ciphers
[16:29:57 INFO]: Loading plugins...
[16:29:57 ERROR]: Exception in thread "main" com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
[16:29:57 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
[16:29:57 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
[16:29:57 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
[16:29:57 ERROR]:       at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:581)
[16:29:57 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:176)
[16:29:57 ERROR]:       at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
[16:29:57 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
[16:29:57 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
[16:29:57 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:87)
[16:29:57 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:69)
[16:29:57 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:59)
[16:29:57 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:77)
[16:29:57 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:98)
[16:29:57 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:245)
[16:29:57 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:205)
[16:29:57 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:47)
[16:29:57 ERROR]: Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
[16:29:57 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
[16:29:57 ERROR]:       at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
[16:29:57 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:74)
[16:29:57 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
[16:29:57 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
[16:29:57 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
[16:29:57 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
[16:29:57 ERROR]:       ... 20 more
[16:29:57 ERROR]: Caused by: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;
[16:29:57 ERROR]:       at java.lang.Class.getDeclaredFields0(Native Method)
[16:29:57 ERROR]:       at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[16:29:57 ERROR]:       at java.lang.Class.getDeclaredFields(Class.java:1916)
[16:29:57 ERROR]:       at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:760)
[16:29:57 ERROR]:       at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:670)
[16:29:57 ERROR]:       at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
[16:29:57 ERROR]:       at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:88)
[16:29:57 ERROR]:       at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:36)
[16:29:57 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
[16:29:57 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:41)
[16:29:57 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:40)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
[16:29:57 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
[16:29:58 ERROR]:       ... 35 more
[16:29:58 ERROR]: Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
[16:29:58 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66)
[16:29:58 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43)
[16:29:58 ERROR]:       at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[16:29:58 ERROR]:       ... 50 more
`

and it throws the same error even with luckperm.

I know I'm doing something wrong, but I can't figure what, I tried to go to your discord server but the invitation is outdated

**Comment by jehendeoff** [comment]
I tried some forks, but it seems that it is not compatible with 1.14.4 (not the same error tho)
